export enum Action {
  StartReadRequest = "SUBSCRIPTIONS/START_READ_REQUEST",
  GetSubscriptionsSuccess = "SUBSCRIPTIONS/GET_SUBSCRIPTIONS_SUCCESS",
  GetSubscriptionsFailure = "SUBSCRIPTIONS/GET_SUBSCRIPTIONS_FAILURE",

  StartDeleteRequest = "SUBSCRIPTIONS/START_DELETE_REQUEST",
  DeleteSuccess = "SUBSCRIPTIONS/DELETE_SUCCESS",
  DeleteFailure = "SUBSCRIPTIONS/DELETE_FAILURE",

  StartUpdateRequest = "SUBSCRIPTIONS/START_UPDATE_REQUEST",
  UpdateSuccess = "SUBSCRIPTIONS/UPDATE_SUCCESS",
  UpdateFailure = "SUBSCRIPTIONS/UPDATE_FAILURE",
}
