# Name of your application. Used to uniquely configure containers.
service: makerspace-rails

deploy_timeout: 60

# Name of the container image.
image: cjdenio/makerspace-rails

# Deploy to these servers.
servers:
  web:
    - 159.223.202.30

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  app_port: 3000
  ssl: true
  host: makerspace-test.clb.li

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: cjdenio

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  context: .
  args:
    ENVIRONMENT: production

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    MLAB_URI: "mongodb://makerspace-rails-db:27017"
    REDIS_URI: "redis://makerspace-rails-redis:6379/1"
  secret:
    - SECRET_KEY_BASE

accessories:
  db:
    image: mongo
    host: 159.223.202.30
    directories:
      - data:/data/db
  redis:
    image: redis
    host: 159.223.202.30
