export enum Action {
  StartReadRequest = "TRANSACTIONS/START_READ_REQUEST",
  GetTransactionsSuccess = "TRANSACTIONS/GET_TRANSACTIONS_SUCCESS",
  GetTransactionsFailure = "TRANSACTIONS/GET_TRANSACTIONS_FAILURE",

  StartCreateRequest = "TRANSACTIONS/START_CREATE_REQUEST",
  CreateTransactionSuccess = "TRANSACTIONS/CREATE_TRANSACTION_SUCCESS",
  CreateTransactionFailure = "TRANSACTIONS/CREATE_TRANSACTION_FAILURE",

  StartUpdateRequest = "TRANSACTION/START_UPDATE_REQUEST",
  UpdateTransactionSuccess = "TRANSACTION/UPDATE_TRANSACTION_SUCCESS",
  UpdateTransactionFailure = "TRANSACTION/UPDATE_TRANSACTION_FAILURE",

  StartDeleteRequest = "TRANSACTION/START_DELETE_REQUEST",
  DeleteTransactionSuccess = "TRANSACTION/DELETE_TRANSACTION_SUCCESS",
  DeleteTransactionFailure = "TRANSACTION/DELETE_TRANSACTION_FAILURE",
}
