require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TokenController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Token. As you add validations to Token, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TokensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "POST #validate" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested token" do
        token = Token.create! valid_attributes
        put :update, params: {id: token.to_param, token: new_attributes}, session: valid_session
        token.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested token as @token" do
        token = Token.create! valid_attributes
        put :update, params: {id: token.to_param, token: valid_attributes}, session: valid_session
        expect(assigns(:token)).to eq(token)
      end

      it "redirects to the token" do
        token = Token.create! valid_attributes
        put :update, params: {id: token.to_param, token: valid_attributes}, session: valid_session
        expect(response).to redirect_to(token)
      end
    end

    context "with invalid params" do
      it "assigns the token as @token" do
        token = Token.create! valid_attributes
        put :update, params: {id: token.to_param, token: invalid_attributes}, session: valid_session
        expect(assigns(:token)).to eq(token)
      end

      it "re-renders the 'edit' template" do
        token = Token.create! valid_attributes
        put :update, params: {id: token.to_param, token: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Token" do
        expect {
          post :create, params: {token: valid_attributes}, session: valid_session
        }.to change(Token, :count).by(1)
      end

      it "assigns a newly created token as @token" do
        post :create, params: {token: valid_attributes}, session: valid_session
        expect(assigns(:token)).to be_a(Token)
        expect(assigns(:token)).to be_persisted
      end

      it "redirects to the created token" do
        post :create, params: {token: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Token.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved token as @token" do
        post :create, params: {token: invalid_attributes}, session: valid_session
        expect(assigns(:token)).to be_a_new(Token)
      end

      it "re-renders the 'new' template" do
        post :create, params: {token: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

end
