on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mongodb/mongodb-atlas-local:latest
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.9
          bundler-cache: true
      - run: bundle exec rspec
        env:
          MLAB_URI: mongodb://localhost:27017?directConnection=true
          BT_ENV: sandbox
          BT_MERCHANT_ID: ${{ secrets.BT_MERCHANT_ID }}
          BT_PUBLIC_KEY: ${{ secrets.BT_PUBLIC_KEY }}
          BT_PRIVATE_KEY: ${{ secrets.BT_PRIVATE_KEY }}
      - run: bundle exec rake integration
