on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.9
          bundler-cache: true
      - run: bundle exec rspec
        env:
          MLAB_URI: mongodb://localhost:27017
      - run: bundle exec rake integration
